//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAN
    {
        public BAN()
        {
            this.HOA_DON = new HashSet<HOA_DON>();
        }
    
        public int SOBAN { get; set; }
        public int SOCHO { get; set; }
        public int TRANGTHAI { get; set; }
        public string TENBAN { get; set; }
    
        public virtual ICollection<HOA_DON> HOA_DON { get; set; }
    }
}
