//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHI_TIET_HOA_DON
    {
        public int MAHD { get; set; }
        public int MATU { get; set; }
        public int SL { get; set; }
        public double GIABAN { get; set; }
    
        public virtual HOA_DON HOA_DON { get; set; }
        public virtual THUC_UONG THUC_UONG { get; set; }
    }
}
