//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAT_HANG
    {
        public int MADDH { get; set; }
        public int MANCC { get; set; }
        public System.DateTime NGAYGIAO { get; set; }
    
        public virtual DON_DAT_HANG DON_DAT_HANG { get; set; }
        public virtual NHA_CUNG_CAP NHA_CUNG_CAP { get; set; }
    }
}
