//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class HANG_HOA
    {
        public HANG_HOA()
        {
            this.CHI_TIET_DON_DAT_HANG = new HashSet<CHI_TIET_DON_DAT_HANG>();
            this.CHI_TIET_PHIEU_NHAP_HANG = new HashSet<CHI_TIET_PHIEU_NHAP_HANG>();
        }
    
        public int MAHH { get; set; }
        public string TENHH { get; set; }
        public string DVT { get; set; }
        public bool TRANGTHAIXOA { get; set; }
        public int SLTON { get; set; }
    
        public virtual ICollection<CHI_TIET_DON_DAT_HANG> CHI_TIET_DON_DAT_HANG { get; set; }
        public virtual ICollection<CHI_TIET_PHIEU_NHAP_HANG> CHI_TIET_PHIEU_NHAP_HANG { get; set; }
    }
}
