//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHAN_VIEN
    {
        public NHAN_VIEN()
        {
            this.DON_DAT_HANG = new HashSet<DON_DAT_HANG>();
            this.HOA_DON = new HashSet<HOA_DON>();
            this.PHIEU_NHAP_HANG = new HashSet<PHIEU_NHAP_HANG>();
            this.TAI_KHOAN = new HashSet<TAI_KHOAN>();
        }
    
        public int MANV { get; set; }
        public string TENNV { get; set; }
        public string DIACHI { get; set; }
        public string SDT { get; set; }
        public bool TRANGTHAIXOA { get; set; }
        public string CHUCVU { get; set; }
    
        public virtual ICollection<DON_DAT_HANG> DON_DAT_HANG { get; set; }
        public virtual ICollection<HOA_DON> HOA_DON { get; set; }
        public virtual ICollection<PHIEU_NHAP_HANG> PHIEU_NHAP_HANG { get; set; }
        public virtual ICollection<TAI_KHOAN> TAI_KHOAN { get; set; }
    }
}
