//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class THUC_UONG
    {
        public THUC_UONG()
        {
            this.CHI_TIET_HOA_DON = new HashSet<CHI_TIET_HOA_DON>();
        }
    
        public int MATU { get; set; }
        public string TENTU { get; set; }
        public int MALOAITU { get; set; }
        public double GIA { get; set; }
        public bool TRANGTHAIXOA { get; set; }
    
        public virtual ICollection<CHI_TIET_HOA_DON> CHI_TIET_HOA_DON { get; set; }
        public virtual LOAI_THUC_UONG LOAI_THUC_UONG { get; set; }
    }
}
